name: AdvancedGift
main: io.github.TrekkieEnderman.advancedgift.AdvancedGift
version: ${project.version}
author: "TrekkieEndermom (Old name: TrekkieEnderman)"
website: https://www.spigotmc.org/resources/advancedgift-1-8-8.46458/
api-version: 1.21.11

permissions:
  advancedgift.gift.send:
    description: Allows sending gifts
    default: true
    children:
      advancedgift.gift.receive: true
  advancedgift.gift.message:
    description: Allows attaching messages to gifts
    default: true
  advancedgift.gift.spy:
    description: Allows spying on gift exchanges
    default: op
  advancedgift.bypass.cooldown:
    description: Allows bypassing the gift cooldown
    default: false
  advancedgift.bypass.world.restriction:
    description: Allows bypassing the restriction on sending gifts between groups of worlds
    default: false
  advancedgift.bypass.world.blacklist:
    description: Allows sending and receiving gifts while in a blacklisted world
    default: false
  advancedgift.bypass.vanish:
    description: Allows sending gifts to hidden players
    default: op
  advancedgift.reload:
    description: Allows reloading AdvancedGift's configuration files
    default: op
  advancedgift.translate:
    description: Allows creating customizable translation files for this plugin
    default: op